node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build jar') {
	dir ('intake'){
		/var/jenkins_home/tools/hudson.plugins.gradle.GradleInstallation/gradle-5.0/bin/gradle build	
	}
    }


}
