node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build jar') {
	dir ('intake'){
		sh """
		/var/jenkins_home/tools/hudson.plugins.gradle.GradleInstallation/gradle-5.0/bin/gradle build	
		"""
	}
    }

    stage('Build image') {
 	dir ('intake'){
        	app = docker.build("intake")
	}
    }
    
   stage('Push image') {
        docker.withRegistry('http://nexus3-registry.okd.pyramidchallenges.com/docker-devt/my-image', '0be12b2b-d89f-405d-bd08-cbfaceebe02d') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }

}
